### ISSUE TITLE
Doesn't work on apache 2.4.18 

### ISSUE THREAD

**Issue by RYNEQ** [markusju/mod_mptcp#1]
Hi 
I tried to build your module for my apache server ( version 2.4.18 - Ubuntu ) 
But it seems they are not compatible 
Apache's child process crashes when MOD_MPTCP is enabled!

`AH00051: child pid 26568 exit signal Aborted (6), possible coredump in /etc/apache2` 

I attached the apache's dump from logs

what is the problem? 
is your MPTCP module only compatible with specific versions of apache?

[apache_dump_mptcp.txt.gz](https://github.com/markusju/mod_mptcp/files/1376530/apache_dump_mptcp.txt.gz)

**Comment by markusju** [comment]
Hi RYNEQ,

thank you for trying out my plugin. I just looked into the issue. It seems that you are not using a MPTCP-Linux Kernel thus causing the call to gestsockopt() to fail and read random memory segments, potentially overflowing the string buffer I am using to transfer the return value into an environment variable.

Unfortunately, I was stupid enough not to check the return value of 'getsockopt()' for error codes, which could have avoided this issue. I have fixed this and the plugin will set the environment variable to '0' if the call to gestsockopt() fails.

Please let me know if you indeed did have the Linux Kernel extension for MPTCP installed, which may indicate another issue.

I have successfully tested the plugin on a Ubuntu 16.04.3 LTS Linux 4.4.83.mptcp and Apache 2.4.18
